CREATE TABLE artists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    artist_name TEXT NOT NULL,
    genius_id INTEGER NOT NULL,
    CONSTRAINT artist_genius_id_unique UNIQUE (genius_id)
);

CREATE TABLE songs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    song_url TEXT NOT NULL,
    themes TEXT NOT NULL,
    lyrics TEXT NOT NULL,
    genius_id INTEGER NOT NULL,
    artist_id INTEGER NOT NULL,
    FOREIGN KEY (artist_id) REFERENCES artists (genius_id),
    CONSTRAINT song_genius_id_unique UNIQUE (genius_id)
);